services:
  yummy-bot-3:
    image: pischule/yummy-bot-3
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - './data:/usr/src/app/data'
      - './config:/usr/src/app/config'
